#!/usr/bin/env bash
# configure a new ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
service nginx start
