#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.
#`Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number In a list format
cnt=1;
while [ $cnt -le 100 ]
do
	if ! (( cnt%15 ))
	then
		echo "FizzBuzz"
	elif ! (( cnt%3 ))
	then
		echo "Fizz"
	elif ! (( cnt%5 ))
	then
		echo "Buzz"
	else
		echo $cnt
	fi
	let cnt=cnt+1
done
