#!/usr/bin/env bash
# a Bash script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School and
# then Hi on a new line.
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
	    echo "bad luck"
	elif [ $i -eq 8 ]
	then
	    echo "good luck"
	else
	    echo "Holberton School"
	fi
	let i=i+1
done
