#!/usr/bin/env bash
# a Bash script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School and
# then Hi on a new line.
i=1
while [ $i -le 20 ]
do
        case $i in
	    5) echo "bad luck from China";;
	    10) echo "bad luck from Japan";;
	    18) echo "bad luck from Italy";;
	esac
	echo $i
	let i=i+1
done
