#!/usr/bin/env bash
# a Bash script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School and
# then Hi on a new line.
i=1
while [ $i -le 20 ]
do
	if [ $i -eq 4 ]
	then
	    echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
	    echo "bad luck from Japan"
	elif [ $i -eq 20 ]
	then
	    echo "bad luck from Italy"
	else
	    echo "Holberton School"
	fi
	let i=i+1
done
