#!/usr/bin/env bash
# script that installs and configues ufw
sudo apt-get -y install ufw
sudo ufw disable
sudo ufw default deny incomint
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
