#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server
# with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new
sed -i -e "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
sed -i "\$a 8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
