#!/usr/bin/env bash
# script that runs nginx as user nginx
pkill apache2
chmod -R nginx /etc/nginx
chmod 777 -R /etc/nginx/
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
